name: final_test_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.1
  firebase_core: ^2.4.0
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  http: ^0.13.5
  badges: ^2.0.3
  smooth_page_indicator: ^1.0.0+2
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
#  flutter_simple_rating_bar: ^0.0.3
  readmore: ^2.2.0
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  pay: ^1.0.11
  cached_network_image: ^3.2.3
  mocktail: ^0.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #